/*
 * Generated by TASKING Pin Mapper for AURIX
 * - device  : TC38XPD
 * - package : LFBGA292
 */

#include "aurix_pin_mappings.h"


/* GPIO pin configuration */

static const IfxPort_Io_ConfigPin gpio_pin_table[] = 
{
    IFXCFG_P02_4_IO_CONFIG
};

static const IfxPort_Io_Config gpio_io_config_table = 
{
    sizeof(gpio_pin_table)/sizeof(IfxPort_Io_ConfigPin),
    (IfxPort_Io_ConfigPin*)gpio_pin_table
};

extern void gpio_init_pins(void)
{
    IfxPort_Io_initModule(&gpio_io_config_table);
}


/* CAN0 pin configuration */

static const IfxPort_Io_ConfigPin can0_pin_table[] = 
{
    IFXCFG_P02_5_IO_CONFIG
};

static const IfxPort_Io_Config can0_io_config_table = 
{
    sizeof(can0_pin_table)/sizeof(IfxPort_Io_ConfigPin),
    (IfxPort_Io_ConfigPin*)can0_pin_table
};

extern void can0_init_pins(void)
{
    IfxPort_Io_initModule(&can0_io_config_table);
}

